name: musician_organizer
description: A new Flutter project for a musician organizer app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
